---
- name: Gather OS-Info
  hosts: linux_hosts
  gather_facts: no
  tasks:
    - name: Task Gather OS Distro
      setup: filter='ansible_dist*'
      register: facts
    - debug: var=facts
    - local_action: shell echo "{{facts.ansible_facts.ansible_distribution}}" > ~/Ansible_CaC/output.txt