---
- name: Verify Redis is installed and copy redis.conf and sentinel.conf file
  hosts:
  - host10
  - host06
  - host07
  vars:
    port: 26379
  tasks:
    - name: Check if Redis CLI is accessible
      ansible.builtin.shell:
        cmd: "redis-cli INFO"
        executable: /bin/bash
      register: redis_cli
      failed_when: redis_cli.rc != 0
    
    - name: Extract Path
      ansible.builtin.shell:
        cmd: "redis-cli INFO | sed -n 's/^config_file:\\s*//p'"
        executable: /bin/bash
      register: redis_path

    - name: Redis Config Path
      when: redis_path is succeeded
      ansible.builtin.debug:
        var: redis_path

    - name: Copy Redis configuration file
      when: redis_path is succeeded
      fetch:
        src: "{{ redis_path.stdout }}"
        dest: ~/Ansible_CaC/redis

    - name: Check if Redis Sentinel is accessible
      ansible.builtin.shell:
        cmd: "redis-cli -p {{ port }} INFO"
        executable: /bin/bash
      register: redis_cli_sentinel
      failed_when: redis_cli_sentinel.rc != 0
    
    - name: Extract Path
      ansible.builtin.shell:
        cmd: "redis-cli -p {{ port }} INFO | sed -n 's/^config_file:\\s*//p'"
        executable: /bin/bash
      register: redis_sentinel_path

    - name: Redis Sentinel Config Path
      when: redis_sentinel_path is succeeded
      ansible.builtin.debug:
        var: redis_sentinel_path

    - name: Copy Redis Sentinel configuration file
      when: redis_sentinel_path is succeeded
      fetch:
        src: "{{ redis_sentinel_path.stdout }}"
        dest: ~/Ansible_CaC/redis

